name: Build and Test

on:
  pull_request:
    branches:
      - master

  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Build
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
      run: |
        npm run build
        npm run export
    - uses: actions/cache@v2
      id: restore-export
      with:
        path: ./out
        key: ${{ github.sha }}
