name: Deploy to Github Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/cache@v3
      id: restore-export
      with:
        path: ./out
        key: ${{ github.sha }}
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out